### ISSUE TITLE
where is the file 'tamil'?

### ISSUE THREAD

**Issue by neotamizhan** [nithyadurai87/tamil-sandhi-checker#2]
A library called 'tamil' is imported in the given code. Can you please add that to the repository?

**Comment by nithyadurai87** [comment]
https://github.com/Ezhil-Language-Foundation/open-tamil

here is the library.

install it using

pip install open-tamil

2018-03-04 15:58 GMT+05:30 Siddharth Venkatesan <notifications@github.com>:

**Comment by arcturusannamalai** [comment]
I think you may close this issue, to indicate it is resolved.
